# Site settings
title: Yi Zhao
email: zhaoyi.zero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little site, for fun things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zaopuppy.github.io" # the base hostname & protocol for your site
twitter_username: zhaoyi414
github_username:  zaopuppy

# Build settings
markdown: kramdown

